### ISSUE TITLE
[DOCS] : Create CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Susmita-Dey** [XollabOS/talktometechnology#21]
CODE_OF_CONDUCT.md file needs to added to the repository to let people know about the CODE_OF_CONDUCT while contributing to this repo.

**Comment by abh139** [comment]
there is an issue already created

**Comment by Susmita-Dey** [comment]
> there is an issue already created

Issue #19 is not same and mine is not duplicate one.

**Comment by abh139** [comment]
Okay

**Comment by dnsmichi** [comment]
Example: https://github.com/EddieHubCommunity/.github/blob/main/CODE_OF_CONDUCT.md - requires an email address to contacts.

**Comment by dnsmichi** [comment]
https://github.com/XollabOS/.github/pull/9

**Comment by laurelayounis** [comment]
Added a code of conduct thank you everyone for the suggestion and opening the issue for it.
