### ISSUE TITLE
Add explanation of colours

### ISSUE THREAD

**Issue by emmalearnscode** [XollabOS/talktometechnology#29]
What do the colours mean? It would be great to have an explanation of that somewhere.

**Comment by laurelayounis** [comment]
Great idea to add an explanation of the colors. The board uses the Fitzgerald Key Groups parts of speech:
Blue: adjectives
Green: verbs
Yellow: pronouns
Orange: nouns
White: conjunctions
Pink: questions
Brown: Adverbs
Red: important function words, negation, emergency words. 
We will be adding this information to the readme doc, we will also need to update the color of the tiles in the board to ensure they're in the correct color scheme. Thank you Emma.
