### ISSUE TITLE
ci: Security scanning

### ISSUE THREAD

**Issue by dnsmichi** [XollabOS/talktometechnology#33]
## Proposal

Add security scanning into PRs

- Code scanning
- Secrets
- Dependencies

**Comment by dnsmichi** [comment]
#44 enables CodeQL for static security testing (SAST).

@codebymatthew @laurelayounis  I've also enabled Dependabot in the project settings. This might not immediately have an impact until a dependency management framework is enabled (NodeJS package.json, etc.). Instead, it comes in preparation for later refactoring. 

![image](https://user-images.githubusercontent.com/382049/164229168-2cb40145-b0b6-49fa-808f-ffe1a209dbd6.png)

**Comment by laurelayounis** [comment]
This is amazing! Thank you for all your hard work.
