### ISSUE TITLE
Card layout inconsistent on smaller screen sizes

### ISSUE THREAD

**Issue by pan-alex** [XollabOS/talktometechnology#52]
## Problem to solve

On smaller screen sizes (<1000px; gets worse with smaller screen sizes until layout is reset by a media query), the layout becomes inconsistent:
- differences in card width & spacing
- differences in number of cards per row

It is slightly unpleasant to look at but also makes it hard to find cards when the layout is inconsistent.

iPhone 5 viewport: 320 x 568
<img src='https://user-images.githubusercontent.com/26422273/166391623-116dab27-78a0-4082-9529-6bc4fbc91538.png' height=300px>

iPhone 6/7/8 viewport: 414 x 736
<img src='https://user-images.githubusercontent.com/26422273/166391620-a2daf498-598f-45bd-8ae8-c6cfab2a918b.png' height=300px>

## Proposal

Potential solutions:
- Adjust the overall layout to force consistent card sizes (e.g., using grid)
- A less intrusive option could be:
    - Add additional media queries for # of cards per row and font sizes
    - Add variable font-sizes for larger words

## Tasks

- [  ] If okay with the potential solutions, this can be assigned to me

**Comment by laurelayounis** [comment]
Merged your update into the code base to fix this issue thank you for your contribution great work!
