### ISSUE TITLE
docs: Gitpodify the project

### ISSUE THREAD

**Issue by Pradumnasaraf** [XollabOS/talktometechnology#8]
official [docs](https://www.gitpod.io/docs/config-gitpod-file) for the refrence

**Comment by Pradumnasaraf** [comment]
> https://www.gitpod.io/blog/gitpodify 

That's a great blog didn't know about it, thank you for sharing.

**Comment by dnsmichi** [comment]
Related to extending Gitpod: https://about.gitlab.com/blog/2021/07/19/teams-gitpod-integration-gitlab-speed-up-development/

**Comment by dnsmichi** [comment]
Serving static HTML - use a simple HTTP web server, following https://www.gitpod.io/docs/languages/html
