### ISSUE TITLE
Add instructions for how to start project

### ISSUE THREAD

**Issue by emmalearnscode** [XollabOS/talktometechnology#9]
Add to the readme steps to fork, clone and start the project on your own machine.

**Comment by laurelayounis** [comment]
Just added a guide of how to get started that goes over how to fork, clone and start the project, thank you for raising this issue Emma.

**Comment by dnsmichi** [comment]
@laurelayounis I cannot see the changes, maybe they slipped. For future workflows, I'd suggest always linking the Pull Request before closing an issue. 

For this specific issue, I'll work on a PR to add the instructions and specifically how to run a webserver to develop the software locally, in containers, or in Gitpod.

Related to #8

**Comment by laurelayounis** [comment]
thank you @dnsmichi for doing this also really great advice, I'll make sure to start linking the pull request before closing an issue.
